### ISSUE TITLE
Иконки к задачам и группировку задавать в БД

### ISSUE THREAD

**Issue by Joker-HD** [yenesey/Synapse#2]
Иконки к задачам и группировку нужно задавать в БД.
Это позволит изменить визуализацию задач без необходимости сборки.
К тому же эта информация больше относится к самой задаче, нежели к ее форме VUE

**Comment by yenesey** [comment]
Можно скачивать и пробовать.
В базе изменения такие:
[objects]
95	menu	cb	Отчетность ЦБ
96	menu	fns	ФНС
97	menu	cd	Работа с CD
98	menu	test	Тестирование

[meta] - желательно добавить ограничение на уникальность первого поля (object), т.е. для одного объекта, одна сущьность метаданных
метаданные приняли такой вид, думаю по смыслу разберешься
101	{"section": "cb"}
33	{"constraint" : {"column":"C_1", "operator":"like", "class":"deps"}}
35	{"constraint" : {"column":"C_3", "operator":"like", "class":"deps"}}
48	{"dwr":"172.22.1.16", "dirEHD":"\\\\kr-fs-05\\Common\\Archive\\CFT\\EAC"}
49	{"dirEHD":"\\\\irk-fs-01\\Common\\Archive\\CFT\\EAC"}
55	{"constraint" : {"column":"C_1", "operator":"like", "class":"deps"}}
96	{"icon":"account_balance"}
95	{"icon":"account_balance"}

**Comment by Joker-HD** [comment]
может изменит структуру таблицы с метаданными?
Сделать поля: object, meta_name, meta_data.
Причем на одну задачу может быть несколько метаданных, которые потом будут собираться в один объект.
Например:
101	section	cb
33	constraint	{"column":"C_1", "operator":"like", "class":"deps"}
35	constraint	{"column":"C_3", "operator":"like", "class":"deps"}
49	dirEHD	\\irk-fs-01\Common\Archive\CFT\EAC
96	section	fns
96	icon	account_balance

**Comment by yenesey** [comment]
может с точки зрения лазания по таблице это и удобно, но нет. это совершенно лишняя сложность структуры. в конце концов sqlite studio есть режим редактирования в виде формы - там json править удобно.

**Comment by yenesey** [comment]
добавлено:
(class=menu name=default) заводить не обязательно, если его нет - добавляется программно
группы сортируются по id, поэтому, в базе можно задавать также и порядок следования групп "menu"

**Comment by Joker-HD** [comment]
чё-то ты намудрил в system.js

C:\xtech\synapse_dev\core\system.js:156
			return {	...obj,  ...meta}
			        	^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xtech\synapse_dev\app.js:124:1)

**Comment by yenesey** [comment]
Версия node старая похоже у тебя. Обнови на 10 уже

**Comment by Joker-HD** [comment]
после обновления winax похоже не работает
unhandled promise rejection:
{ Error: CreateInstance: Oxch.CInterfaces ?? ??????? ????? ????????? ????.

    at Object.ibso.oxch (C:\xtech\synapse\core\ibso.js:128:13)
    at module.exports (C:\xtech\synapse\tasks\??????? ? FIO.js:18:7)
    at require.then.system (C:\xtech\synapse\tasks\$launcher.js:20:20) errno: -2147024894 }

**Comment by yenesey** [comment]
обновление node всегда влечет за собой 
npm install

**Comment by Joker-HD** [comment]
не могу задать иконку на группу (menu). Отсюда похоже наследование иконки на задачи внутри не происходит.
Предлагаю задавать иконку группам так же через метаданные
